# Generated by Django 5.1.5 on 2025-02-11 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_tests_specialization_name_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="name",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="name",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
