# Generated by Django 5.1.5 on 2025-02-13 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_uploadeddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="doct",
            name="patients",
            field=models.ManyToManyField(
                related_name="doctors", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="name",
            name="role",
            field=models.CharField(
                choices=[("patient", "Patient"), ("doctor", "Doctor")],
                default="patient",
                max_length=20,
            ),
        ),
    ]
