# Generated by Django 5.1.5 on 2025-02-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_doct_patients_name_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doct",
            name="tests",
        ),
    ]
