# Generated by Django 5.1.5 on 2025-02-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_doct_patients_doct_patien"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="name",
            name="specialization",
        ),
        migrations.AddField(
            model_name="name",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="name",
            name="age",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="name",
            name="full_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="name",
            name="profession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="name",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="name",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="name",
            name="name",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
    ]
