# Generated by Django 5.1.5 on 2025-02-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_tests_bloodtest_tests_aggravation_tests_area_of_pain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tests",
            name="ilaj",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
