# Generated by Django 5.2.3 on 2025-06-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_tests_ilaj"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDeletionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=20)),
                ("deletion_date", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(default="Automatic expiration", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Deletion Log",
                "verbose_name_plural": "Deletion Logs",
            },
        ),
    ]
