# Generated by Django 5.2.3 on 2025-07-02 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_tests_armpain"),
    ]

    operations = [
        migrations.AddField(
            model_name="name",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="name",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
