# Generated by Django 5.1.5 on 2025-02-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tests",
            name="specialization",
            field=models.CharField(
                choices=[("dentist", "Dentist"), ("orthopedic", "Orthopedic")],
                default="dentist",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Doct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[("dentist", "Dentist"), ("orthopedic", "Orthopedic")],
                        default="dentist",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tests",
                    models.ManyToManyField(related_name="doctors", to="myapp.tests"),
                ),
            ],
        ),
    ]
