# Generated by Django 5.1.5 on 2025-02-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_tests_specialization_doct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tests",
            name="specialization",
        ),
        migrations.AddField(
            model_name="name",
            name="specialization",
            field=models.CharField(
                choices=[("dentist", "Dentist"), ("orthopedic", "Orthopedic")],
                default="dentist",
                max_length=100,
            ),
        ),
    ]
