# Generated by Django 5.1.5 on 2025-02-13 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_remove_doct_tests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doct",
            name="patients",
        ),
        migrations.AddField(
            model_name="doct",
            name="patien",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
