# Generated by Django 5.1.5 on 2025-02-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_remove_name_specialization_name_address_name_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tests",
            name="Bloodtest",
            field=models.FileField(blank=True, null=True, upload_to="blood_reports/"),
        ),
        migrations.AddField(
            model_name="tests",
            name="aggravation",
            field=models.CharField(
                blank=True,
                choices=[("Activity", "Activity"), ("Rest", "Rest")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="area_of_pain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Neck", "Neck"),
                    ("Upper back", "Upper back"),
                    ("Lower back", "Lower back"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="cause_of_pain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fever", "Fever"),
                    ("Injury", "Injury"),
                    ("Spontaneous", "Spontaneous"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="ctscan",
            field=models.FileField(blank=True, null=True, upload_to="ctscan/"),
        ),
        migrations.AddField(
            model_name="tests",
            name="grip",
            field=models.CharField(
                blank=True, choices=[("Weak", "Weak"), ("Good", "Good")], max_length=20
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="numbness",
            field=models.CharField(
                blank=True,
                choices=[("At rest", "At rest"), ("At work", "At work")],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="past_history",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diabetes Mellitus (DM)", "Diabetes Mellitus (DM)"),
                    ("Hypertension (HTN)", "Hypertension (HTN)"),
                    ("Heart problem", "Heart problem"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="relief",
            field=models.CharField(
                blank=True,
                choices=[("Activity", "Activity"), ("Rest", "Rest")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="support",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tests",
            name="urine_control",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tests",
            name="walking_tolerance",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tests",
            name="xray",
            field=models.FileField(blank=True, null=True, upload_to="xray/"),
        ),
    ]
