# Generated by Django 5.2.3 on 2025-07-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_accountdeletionlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountdeletionlog",
            options={},
        ),
        migrations.RemoveField(
            model_name="tests",
            name="urine_control",
        ),
        migrations.AddField(
            model_name="tests",
            name="GRIP_CHOICES",
            field=models.CharField(
                blank=True, choices=[("Weak", "Weak"), ("Good", "Good")], max_length=20
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="arm",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="tests",
            name="cutdownactivities",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="tests",
            name="examination",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="tests",
            name="living_with_pain",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="tests",
            name="neckPain",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="tests",
            name="neck_problems_work_leave",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="tests",
            name="neckpain_inteference",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="tests",
            name="pain_trouble",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="tests",
            name="quality_of_life",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="accountdeletionlog",
            name="reason",
            field=models.CharField(default="Inactivity", max_length=100),
        ),
        migrations.AlterField(
            model_name="tests",
            name="grip",
            field=models.CharField(
                blank=True, choices=[("Weak", "Weak"), ("Good", "Good")], max_length=10
            ),
        ),
    ]
