# Generated by Django 5.2.3 on 2025-07-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_alter_accountdeletionlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tests",
            name="armPain",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
