# Generated by Django 5.2.5 on 2026-01-20 08:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_name_created_at_name_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="doct",
            name="bio",
            field=models.TextField(blank=True, help_text="Short professional summary"),
        ),
        migrations.AddField(
            model_name="doct",
            name="consultation_fee",
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="doct",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doct",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doct",
            name="hospital_name",
            field=models.CharField(default="City Hospital", max_length=200),
        ),
        migrations.AddField(
            model_name="doct",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Toggles the green checkmark badge"
            ),
        ),
        migrations.AddField(
            model_name="doct",
            name="languages",
            field=models.CharField(
                default="English, Urdu", help_text="Comma separated", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="doct",
            name="patients_treated",
            field=models.CharField(default="1k+", help_text="e.g. 5k+", max_length=20),
        ),
        migrations.AddField(
            model_name="doct",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="doct",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="default_doctor.png", upload_to="doctor_pics/"
            ),
        ),
        migrations.AddField(
            model_name="doct",
            name="rating",
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name="doct",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doct",
            name="success_rate",
            field=models.CharField(default="98%", max_length=10),
        ),
        migrations.AddField(
            model_name="doct",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="doct",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="doct",
            name="specialization",
            field=models.CharField(
                help_text="e.g., Cardiologist, Dermatologist", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="DoctorEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(help_text="e.g. MBBS, FCPS", max_length=100),
                ),
                ("institution", models.CharField(max_length=200)),
                ("start_year", models.CharField(max_length=4)),
                (
                    "end_year",
                    models.CharField(
                        help_text="Enter 'Present' if ongoing", max_length=10
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="myapp.doct",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_year"],
            },
        ),
        migrations.CreateModel(
            name="DoctorExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(help_text="e.g. Senior Surgeon", max_length=100),
                ),
                ("hospital", models.CharField(max_length=200)),
                ("start_year", models.CharField(max_length=4)),
                (
                    "end_year",
                    models.CharField(
                        help_text="Enter 'Present' if ongoing", max_length=10
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="myapp.doct",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_year"],
            },
        ),
    ]
