# Generated by Django 5.2.5 on 2026-01-20 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_doct_bio_doct_consultation_fee_doct_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doct",
            name="patien",
        ),
        migrations.AlterField(
            model_name="doct",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
