# Generated by Django 5.2.5 on 2026-01-20 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_remove_doct_patien_alter_doct_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doct",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RemoveField(
            model_name="doct",
            name="specialization",
        ),
        migrations.AddField(
            model_name="doct",
            name="specialty",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="e.g., Cardiologist",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doct",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="doct",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="doct",
            name="languages",
            field=models.CharField(default="English, Urdu", max_length=200),
        ),
        migrations.AlterField(
            model_name="doct",
            name="patients_treated",
            field=models.CharField(default="1k+", max_length=20),
        ),
        migrations.AlterField(
            model_name="doctoreducation",
            name="degree",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="doctoreducation",
            name="end_year",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="doctorexperience",
            name="end_year",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="doctorexperience",
            name="position",
            field=models.CharField(max_length=100),
        ),
    ]
