# Generated by Django 5.2.5 on 2026-01-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_rename_name_doct_full_name_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="name",
            managers=[],
        ),
    ]
