# Generated by Django 5.2.5 on 2026-01-21 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_alter_name_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="doct",
            name="patient_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doct",
            name="patients",
            field=models.ManyToManyField(
                blank=True, related_name="doctors", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="addanswer1",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="tests",
            name="addanswer2",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="tests",
            name="addanswer3",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="tests",
            name="addquestion1",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="tests",
            name="addquestion2",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="tests",
            name="addquestion3",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="tests",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor",
                to="myapp.doct",
            ),
        ),
        migrations.RemoveField(
            model_name="tests",
            name="past_history",
        ),
        migrations.AddField(
            model_name="tests",
            name="past_history",
            field=models.ManyToManyField(blank=True, to="myapp.medicalcondition"),
        ),
    ]
